### ISSUE TITLE
作者可以分享一下你的环境么

### ISSUE THREAD

**Issue by yfq512** [mryuan0428/Title_Generator_CN#1]

**Comment by OldMy** [comment]
Traceback (most recent call last):
  File "seq2seq_train.py", line 281, in <module>
    x = OurBidirectional(CuDNNLSTM(z_dim // 2, return_sequences=True))([x, x_mask])
  File "/data/zhu/.conda/envs/mustard/lib/python3.7/site-packages/keras/engine/base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "seq2seq_train.py", line 145, in call
    x_backward = self.reverse_sequence(x, mask)
  File "seq2seq_train.py", line 141, in reverse_sequence
    return K.tf.reverse_sequence(x, seq_len, seq_dim=1)
AttributeError: module 'keras.backend' has no attribute 'tf'

hello，您的问题解决了么

**Comment by fp674018495** [comment]
+1

**Comment by OldMy** [comment]
> +1

请问搞定环境了么？
